name: sale_insight
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^21.1.41
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  dio: ^4.0.4
  dio_network_exceptions:
    path: packages/dio_network_exceptions
  sales_data:
    path: packages/sales_data
  flutter_native_splash: ^2.2.19
  fl_chart: ^0.62.0
  flutter_charts: ^0.5.1
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/sales-insight-splash.png"
  fullscreen: true
  color: "#E5E5E5"

flutter_icons:
  android: true
  image_path: "assets/images/sales-insight.jpg"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/sales-insight.jpg'